// This file is @generated by prost-build.
#[derive(derive_builder::Builder)]
#[derive(custom_proto::Input)]
#[derive(Clone, PartialEq, Eq, Hash, ::defiant::View)]
pub struct Message<'arena> {
    #[defiant(string, tag = "1")]
    pub say: &'arena str,
}
#[derive(derive_builder::Builder)]
#[derive(custom_proto::Output)]
#[derive(Clone, PartialEq, Eq, Hash, ::defiant::View)]
pub struct Response<'arena> {
    #[defiant(string, tag = "1")]
    pub say: &'arena str,
}
#[some_enum_attr(u8)]
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::defiant::Enumeration)]
#[repr(i32)]
pub enum ServingStatus {
    Unknown = 0,
    Serving = 1,
    NotServing = 2,
}
impl ServingStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unknown => "UNKNOWN",
            Self::Serving => "SERVING",
            Self::NotServing => "NOT_SERVING",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "UNKNOWN" => Some(Self::Unknown),
            "SERVING" => Some(Self::Serving),
            "NOT_SERVING" => Some(Self::NotServing),
            _ => None,
        }
    }
}
