// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::defiant::View)]
pub struct OutdirRequest<'arena> {
    #[defiant(string, tag = "1")]
    pub query: &'arena str,
    #[defiant(int32, tag = "2")]
    pub page_number: i32,
    #[defiant(int32, tag = "3")]
    pub result_per_page: i32,
}
