// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::defiant::Message)]
pub struct Container {
    #[defiant(oneof = "container::Data", tags = "1, 2")]
    pub data: ::core::option::Option<container::Data>,
}
/// Nested message and enum types in `Container`.
pub mod container {
    #[derive(Clone, PartialEq, Eq, Hash, ::defiant::Oneof)]
    pub enum Data {
        #[defiant(message, tag = "1")]
        Foo(super::Foo),
        #[defiant(message, tag = "2")]
        Bar(super::Bar),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::defiant::Message)]
pub struct Foo {
    #[defiant(string, tag = "1")]
    pub foo: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::defiant::Message)]
pub struct Bar {
    #[defiant(message, optional, tag = "1")]
    pub qux: ::core::option::Option<Qux>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::defiant::Message)]
pub struct Qux {
}
