// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::defiant::Message)]
pub struct Container<'arena> {
    #[prost(oneof = "container::Data", tags = "1, 2")]
    pub data: ::core::option::Option<container::Data<'arena>>,
}
/// Nested message and enum types in `Container`.
pub mod container {
    #[derive(Clone, PartialEq, Eq, Hash, ::defiant::Oneof)]
    pub enum Data<'arena> {
        #[prost(message, tag = "1")]
        Foo(super::Foo<'arena>),
        #[prost(message, tag = "2")]
        Bar(super::Bar),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::defiant::Message)]
pub struct Foo<'arena> {
    #[prost(string, tag = "1")]
    pub foo: &'arena str,
}
#[derive(Clone, PartialEq, Eq, Hash, ::defiant::Message)]
pub struct Bar<'arena> {
    #[prost(message, optional, tag = "1")]
    pub qux: ::core::option::Option<&'arena Qux>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::defiant::Message)]
pub struct Qux {
}
