// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::defiant::View)]
pub struct Container<'arena> {
    #[defiant(oneof = "container::Data", tags = "1, 2")]
    pub data: ::core::option::Option<container::Data<'arena>>,
}
/// Nested message and enum types in `Container`.
pub mod container {
    #[derive(Clone, PartialEq, Eq, Hash, ::defiant::Oneof)]
    pub enum Data<'arena> {
        #[defiant(message, tag = "1")]
        Foo(&'arena super::Foo<'arena>),
        #[defiant(message, tag = "2")]
        Bar(super::Bar),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::defiant::View)]
pub struct Foo<'arena> {
    #[defiant(string, tag = "1")]
    pub foo: &'arena str,
}
#[derive(Clone, PartialEq, Eq, Hash, ::defiant::View)]
pub struct Bar {
    #[defiant(message, optional, tag = "1")]
    pub qux: ::core::option::Option<Qux>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::defiant::View)]
pub struct Qux {
}
